# Generated by Django 4.1.1 on 2022-09-06 13:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=200, verbose_name='specialty')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Date start')),
                ('date_end', models.DateField(auto_now_add=True, verbose_name='Date end')),
                ('college', models.CharField(max_length=200, verbose_name='university or college name')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200, verbose_name='Post')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Date start')),
                ('date_end', models.DateField(auto_now_add=True, verbose_name='Date end')),
                ('company', models.CharField(max_length=200, verbose_name='company name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, verbose_name='Skill name')),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('color', colorfield.fields.ColorField(default='#1967ee', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='persons', verbose_name='Image')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job title')),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='persons', verbose_name='Image')),
                ('contenu', models.TextField(verbose_name='Contenu')),
            ],
        ),
    ]
