# Generated by Django 4.1.1 on 2022-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muadh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_end',
            field=models.DateField(verbose_name='Date end'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_start',
            field=models.DateField(verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_end',
            field=models.DateField(verbose_name='Date end'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_start',
            field=models.DateField(verbose_name='Date start'),
        ),
    ]
