# Generated by Django 4.1.1 on 2022-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muadh', '0002_alter_education_date_end_alter_education_date_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='testimonial',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='url_site',
            field=models.URLField(blank=True, null=True, verbose_name='site url'),
        ),
    ]
