# Generated by Django 4.1.1 on 2022-09-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muadh', '0003_section_testimonial_job_title_testimonial_url_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Site url')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muadh.section')),
            ],
        ),
    ]
